import {
	Assignment,
	Attendance,
	Briefing,
	CabinEntry,
	CabinEntryDetail,
	CabinEntryForm,
	CabinRide,
	CabinRideDetail,
	CabinRideForm,
	CabinRideNew,
	CabinRideNewForm,
	CabinRideNewView,
	CabinRideScan,
	Coaching,
	CoachingForm,
	DailyIncident,
	DailyIncidentForm,
	DailyIncidentView,
	DailyWork,
	DisplayInformationLED,
	Emergency1,
	Emergency2,
	Emergency3,
	Emergency4,
	Emergency5,
	Emergency6,
	Emergency7,
	Emergency8,
	EmergencyForm1,
	EmergencyForm2,
	EmergencyForm3,
	EmergencyForm4,
	EmergencyForm5,
	EmergencyForm6,
	EmergencyForm7,
	EmergencyForm8,
	EmergencyView1,
	EmergencyView2,
	EmergencyView3,
	EmergencyView4,
	EmergencyView5,
	EmergencyView6,
	EmergencyView7,
	EmergencyView8,
	FormChecklistPAwal,
	FormDailyOperation,
	FormKesiapanLintasAwal,
	FormMonitoringScada,
	FormOperasionalHarian,
	FormWSC,
	GonoGoItem,
	HandOver,
	HandOverSpv,
	Home,
	ImportData,
	InformationLED,
	Instruction,
	LangsirForm,
	LangsirList,
	ListChecklistPAwal,
	ListDailyOperation,
	ListKesiapanLintasAwal,
	ListMonitoringScada,
	ListOperasionalHarian,
	ListWSC,
	LogbookNoGoItem,
	LogbookNoGoItemView,
	LogbookWorkOrder,
	MasterCabinRide,
	MasterCabinRideForm,
	MasterDataLrv,
	MasterStation,
	MaterialRefreshing,
	MDEmergency,
	// MDEmergencyForm,
	MDEmergencyView,
	MonthlyRaport,
	MonthlyWork,
	NoGoItem,
	NoGoItemForm,
	NoGoItemView,
	NoKA,
	PPPKAForm,
	PPPKAList,
	PrecisionTrack,
	PreliminaryForm,
	PreliminaryDetail,
	PreliminaryReport,
	PTWList,
	ReportDetailMonthlyWork,
	Scan,
	ScanTablet,
	ScanTakeGiveWork,
	StamformasiForm,
	StamformasiList,
	TakeGiveSupervisor,
	TakeGiveWork,
	TakeGiveWorkTrainDriver,
	TimeTable,
	TrainJourney,
	TrainJourneyReview,
	TrainJourneyTable,
	TrainRoute,
	ViewChecklistPAwal,
	ViewDailyOperation,
	ViewKesiapanLintasAwal,
	ViewMonitoringScada,
	ViewOperasionalHarian,
	ViewWSC,
	WAMForm,
	WAMList,
	WorkOrder,
} from '../Pages/index';

const dataRouters = [
	{
		id: 1,
		name: 'Menu',
		path: '/app/operational',
		page: Home,
	},
	{
		id: 2,
		name: 'TrainJourney',
		path: '/app/operational/trainjourney',
		page: TrainJourney,
	},
	{
		id: 3,
		name: 'Langsir',
		path: '/app/operational/langsir',
		page: LangsirList,
	},
	{
		id: 3,
		name: 'LangsirForm',
		path: '/app/operational/langsir/form',
		page: LangsirForm,
	},
	{
		id: 3,
		name: 'WAM',
		path: '/app/operational/WAM',
		page: WAMList,
	},
	{
		id: 3,
		name: 'WAMForm',
		path: '/app/operational/WAM/form',
		page: WAMForm,
	},

	{
		id: 3,
		name: 'Stamformasi',
		path: '/app/operational/stamformasi',
		page: StamformasiList,
	},
	{
		id: 3,
		name: 'StamformasiForm',
		path: '/app/operational/stamformasi/form',
		page: StamformasiForm,
	},

	{
		id: 3,
		name: 'PPPKA',
		path: '/app/operational/pppka',
		page: PPPKAList,
	},
	{
		id: 3,
		name: 'PPPKAForm',
		path: '/app/operational/pppka/form',
		page: PPPKAForm,
	},
	{
		id: 2,
		name: 'TrainJourneyTable',
		path: '/app/operational/trainjourney/Table',
		page: TrainJourneyTable,
	},
	{
		id: 3,
		name: 'CabinRide',
		path: '/app/operational/cabinride',
		page: CabinRide,
	},
	{
		id: 3,
		name: 'CabinRide',
		path: '/app/operational/cabinride/scan',
		page: CabinRideScan,
	},
	{
		id: 3,
		name: 'CabinRide',
		path: '/app/operational/cabinride/form',
		page: CabinRideForm,
	},
	{
		id: 3,
		name: 'CabinRide',
		path: '/app/operational/cabinride/detail',
		page: CabinRideDetail,
	},
	{
		id: 4,
		name: 'DailyWork',
		path: '/app/operational/dailywork',
		page: DailyWork,
	},
	{
		id: 4,
		name: 'MonthlyWork',
		path: '/app/operational/monthlyWork',
		page: MonthlyWork,
	},
	{
		id: 4,
		name: 'MonthlyWork',
		path: '/app/operational/monthlyWork/import',
		page: ImportData,
	},
	{
		id: 5,
		name: 'MonthlyWork',
		path: '/app/operational/monthlyWork/reportdetail',
		page: ReportDetailMonthlyWork,
	},
	{
		id: 5,
		name: 'TakeGiveWork',
		path: '/app/operational/takegivework',
		page: TakeGiveWork,
	},
	{
		id: 5,
		name: 'TakeGiveWork',
		path: '/app/operational/takegiveworktraindriver',
		page: TakeGiveWorkTrainDriver,
	},
	{
		id: 6,
		name: 'Scan',
		path: '/app/operational/scan',
		page: Scan,
	},
	{
		id: 6,
		name: 'ScanTablet',
		path: '/app/operational/scantablet',
		page: ScanTablet,
	},
	{
		id: 7,
		name: 'ScanTakeGiveWork',
		path: '/app/operational/scantakegivework',
		page: ScanTakeGiveWork,
	},
	{
		id: 8,
		name: 'TrainJourneyReview',
		path: '/app/operational/trainjourneyreview',
		page: TrainJourneyReview,
	},
	{
		id: 9,
		name: 'GonoGoItem',
		path: '/app/operational/gonogoitem',
		page: GonoGoItem,
	},
	{
		id: 12,
		name: 'PreliminaryReport',
		path: '/app/operational/preliminaryreport',
		page: PreliminaryReport,
	},
	{
		id: 12,
		name: 'PreliminaryForm',
		path: '/app/operational/preliminaryreport/form',
		page: PreliminaryForm,
	},
	{
		id: 12,
		name: 'PreliminaryForm',
		path: '/app/operational/preliminaryreport/view',
		page: PreliminaryDetail,
	},
	{
		id: 13,
		name: 'Coaching',
		path: '/app/operational/coaching',
		page: Coaching,
	},
	{
		id: 13,
		name: 'Coaching',
		path: '/app/operational/coaching/form',
		page: CoachingForm,
	},
	{
		id: 14,
		name: 'DailyIncident',
		path: '/app/operational/dailyincident',
		page: DailyIncident,
	},
	{
		id: 14,
		name: 'DailyIncident',
		path: '/app/operational/dailyincident/form',
		page: DailyIncidentForm,
	},
	{
		id: 14,
		name: 'DailyIncident',
		path: '/app/operational/dailyincident/view',
		page: DailyIncidentView,
	},
	{
		id: 10,
		name: 'Briefing',
		path: '/app/operational/briefing',
		page: Briefing,
	},
	{
		id: 11,
		name: 'HandOverSpv',
		path: '/app/operational/handoverspv',
		page: HandOverSpv,
	},
	{
		id: 11,
		name: 'HandOver',
		path: '/app/operational/handover',
		page: HandOver,
	},
	{
		id: 11,
		name: 'Assignment',
		path: '/app/operational/assignment',
		page: Assignment,
	},
	{
		id: 11,
		name: 'HandOver',
		path: '/app/operational/precisiontrack',
		page: PrecisionTrack,
	},
	{
		id: 15,
		name: 'Instruction',
		path: '/app/operational/instruction',
		page: Instruction,
	},
	{
		id: 16,
		name: 'Information LED',
		path: '/app/operational/infoupload',
		page: InformationLED,
	},
	{
		id: 16,
		name: 'MaterialRefreshing',
		path: '/app/operational/infoupload/preview',
		page: DisplayInformationLED,
	},
	{
		id: 16,
		name: 'MaterialRefreshing',
		path: '/app/operational/materialrefreshing',
		page: MaterialRefreshing,
	},

	{
		id: 16,
		name: 'WorkOrder',
		path: '/app/operational/workorder',
		page: WorkOrder,
	},
	{
		id: 16,
		name: 'MonthlyRaport',
		path: '/app/operational/monthlyraport',
		page: MonthlyRaport,
	},
	{
		id: 18,
		name: 'Attendance',
		path: '/app/operational/attendance',
		page: Attendance,
	},

	{
		id: 14,
		name: 'CabinRide',
		path: '/app/operational/admin/cabinride',
		page: MasterCabinRide,
	},
	{
		id: 27,
		name: 'FormCabinRide',
		path: '/app/operational/admin/cabinride/form',
		page: MasterCabinRideForm,
	},

	{
		id: 22,
		name: 'NoKA',
		path: '/app/operational/admin/noka',
		page: NoKA,
	},
	{
		id: 7,
		name: 'TrainRoute',
		path: '/app/operational/admin/trainroute',
		page: TrainRoute,
	},
	{
		id: 6,
		name: 'Station',
		path: '/app/operational/admin/station',
		page: MasterStation,
	},
	{
		id: 4,
		name: 'TimeTable',
		path: '/app/operational/admin/timetable',
		page: TimeTable,
	},

	{
		id: 17,
		name: 'PTW',
		path: '/app/operational/ptw',
		page: PTWList,
	},

	{
		id: 5,
		name: 'NoGoItem',
		path: '/app/operational/nogoitem',
		page: NoGoItem,
	},

	{
		id: 5,
		name: 'FormNoGoItem',
		path: '/app/operational/nogoitem/form',
		page: NoGoItemForm,
	},
	{
		id: 5,
		name: 'ViewNoGoItem',
		path: '/app/operational/nogoitem/detail',
		page: NoGoItemView,
	},

	{
		id: 5,
		name: 'LogbookNoGoItem',
		path: '/app/operational/logbook/nogoitem',
		page: LogbookNoGoItem,
	},
	{
		id: 5,
		name: 'LogbookNoGoItemView',
		path: '/app/operational/logbook/nogoitem/detail',
		page: LogbookNoGoItemView,
	},
	{
		id: 5,
		name: 'LogbookWorkOrder',
		path: '/app/operational/logbook/workorder',
		page: LogbookWorkOrder,
	},
	{
		id: 5,
		name: 'TakeGiveSupervisor',
		path: '/app/operational/takegive/supervisor',
		page: TakeGiveSupervisor,
	},

	{
		id: 6,
		name: 'CabinRideNew',
		path: '/app/operational/cabinridenew',
		page: CabinRideNew,
	},
	{
		id: 6,
		name: 'FormCabinRideNew',
		path: '/app/operational/cabinridenew/form',
		page: CabinRideNewForm,
	},
	{
		id: 6,
		name: 'ViewCabinRideNew',
		path: '/app/operational/cabinridenew/detail',
		page: CabinRideNewView,
	},

	{
		id: 7,
		name: 'MasterDataLrv',
		path: '/app/operational/masterdatalrv',
		page: MasterDataLrv,
	},

	{
		id: 8,
		name: 'CabinEntry',
		path: '/app/operational/cabinentry',
		page: CabinEntry,
	},
	{
		id: 8,
		name: 'CabinEntryDetail',
		path: '/app/operational/cabinentry/detail',
		page: CabinEntryDetail,
	},
	{
		id: 8,
		name: 'CabinEntryForm',
		path: '/app/operational/cabinentry/form',
		page: CabinEntryForm,
	},

	{
		id: 9,
		name: 'Emergency1',
		path: '/app/operational/emergency1',
		page: Emergency1,
	},
	{
		id: 9,
		name: 'EmergencyForm1',
		path: '/app/operational/emergency1/form',
		page: EmergencyForm1,
	},
	{
		id: 9,
		name: 'EmergencyView1',
		path: '/app/operational/emergency1/view',
		page: EmergencyView1,
	},

	{
		id: 10,
		name: 'Emergency2',
		path: '/app/operational/emergency2',
		page: Emergency2,
	},
	{
		id: 10,
		name: 'EmergencyForm2',
		path: '/app/operational/emergency2/form',
		page: EmergencyForm2,
	},
	{
		id: 10,
		name: 'EmergencyView2',
		path: '/app/operational/emergency2/view',
		page: EmergencyView2,
	},

	{
		id: 11,
		name: 'Emergency3',
		path: '/app/operational/emergency3',
		page: Emergency3,
	},
	{
		id: 11,
		name: 'EmergencyForm3',
		path: '/app/operational/emergency3/form',
		page: EmergencyForm3,
	},
	{
		id: 11,
		name: 'EmergencyView3',
		path: '/app/operational/emergency3/view',
		page: EmergencyView3,
	},

	{
		id: 12,
		name: 'Emergency4',
		path: '/app/operational/emergency4',
		page: Emergency4,
	},
	{
		id: 12,
		name: 'EmergencyForm4',
		path: '/app/operational/emergency4/form',
		page: EmergencyForm4,
	},
	{
		id: 12,
		name: 'EmergencyView4',
		path: '/app/operational/emergency4/view',
		page: EmergencyView4,
	},

	{
		id: 13,
		name: 'Emergency5',
		path: '/app/operational/emergency5',
		page: Emergency5,
	},
	{
		id: 13,
		name: 'EmergencyForm5',
		path: '/app/operational/emergency5/form',
		page: EmergencyForm5,
	},
	{
		id: 13,
		name: 'EmergencyView5',
		path: '/app/operational/emergency5/view',
		page: EmergencyView5,
	},

	{
		id: 14,
		name: 'Emergency6',
		path: '/app/operational/emergency6',
		page: Emergency6,
	},
	{
		id: 14,
		name: 'EmergencyForm6',
		path: '/app/operational/emergency6/form',
		page: EmergencyForm6,
	},
	{
		id: 14,
		name: 'EmergencyView6',
		path: '/app/operational/emergency6/view',
		page: EmergencyView6,
	},

	{
		id: 15,
		name: 'Emergency7',
		path: '/app/operational/emergency7',
		page: Emergency7,
	},
	{
		id: 15,
		name: 'EmergencyForm7',
		path: '/app/operational/emergency7/form',
		page: EmergencyForm7,
	},
	{
		id: 15,
		name: 'EmergencyView7',
		path: '/app/operational/emergency7/view',
		page: EmergencyView7,
	},

	{
		id: 15,
		name: 'Emergency8',
		path: '/app/operational/emergency8',
		page: Emergency8,
	},
	{
		id: 15,
		name: 'EmergencyForm8',
		path: '/app/operational/emergency8/form',
		page: EmergencyForm8,
	},
	{
		id: 15,
		name: 'EmergencyView8',
		path: '/app/operational/emergency8/view',
		page: EmergencyView8,
	},

	{
		id: 16,
		name: 'MDEmergency',
		path: '/app/operational/masterData/emergency',
		page: MDEmergency,
	},
	// {
	//   id: 16,
	//   name: 'MDEmergencyForm',
	//   path: '/app/operational/masterData/emergency/form',
	//   page: MDEmergencyForm,
	// },
	{
		id: 16,
		name: 'MDEmergencyView',
		path: '/app/operational/masterData/emergency/view',
		page: MDEmergencyView,
	},

	{
		id: 17,
		name: 'ListWSC',
		path: '/app/operational/wsc',
		page: ListWSC,
	},
	{
		id: 17,
		name: 'FormWSC',
		path: '/app/operational/wsc/form/:type/:id',
		page: FormWSC,
	},
	{
		id: 17,
		name: 'ViewWSC',
		path: '/app/operational/wsc/view',
		page: ViewWSC,
	},
	// {
	// 	id: 17,
	// 	name: 'ListWSC',
	// 	path: '/app/operational/logbook/wsc',
	// 	page: LogbookWSC,
	// },

	{
		id: 19,
		name: 'ListChecklistPAwal',
		path: '/app/operational/pemberangkatanAwal',
		page: ListChecklistPAwal,
	},
	{
		id: 19,
		name: 'FormChecklistPAwal',
		path: '/app/operational/pemberangkatanAwal/form',
		page: FormChecklistPAwal,
	},
	{
		id: 19,
		name: 'ViewChecklistPAwal',
		path: '/app/operational/pemberangkatanAwal/view',
		page: ViewChecklistPAwal,
	},

	{
		id: 20,
		name: 'ListDailyOperation',
		path: '/app/operational/dailyOperations',
		page: ListDailyOperation,
	},
	{
		id: 20,
		name: 'FormDailyOperation',
		path: '/app/operational/dailyOperations/form',
		page: FormDailyOperation,
	},
	{
		id: 20,
		name: 'ViewDailyOperation',
		path: '/app/operational/dailyOperations/view',
		page: ViewDailyOperation,
	},

	{
		id: 21,
		name: 'ListOperasionalHarian',
		path: '/app/operational/masterOperations',
		page: ListOperasionalHarian,
	},
	{
		id: 21,
		name: 'FormOperasionalHarian',
		path: '/app/operational/masterOperations/form',
		page: FormOperasionalHarian,
	},
	{
		id: 21,
		name: 'ViewOperasionalHarian',
		path: '/app/operational/masterOperations/view',
		page: ViewOperasionalHarian,
	},

	{
		id: 22,
		name: 'ListMonitoringScada',
		path: '/app/operational/monitoringScada',
		page: ListMonitoringScada,
	},
	{
		id: 22,
		name: 'FormMonitoringScada',
		path: '/app/operational/monitoringScada/form',
		page: FormMonitoringScada,
	},
	{
		id: 22,
		name: 'ViewMonitoringScada',
		path: '/app/operational/monitoringScada/view',
		page: ViewMonitoringScada,
	},

	{
		id: 23,
		name: 'ListKesiapanLintasAwal',
		path: '/app/operational/kesiapanLintas',
		page: ListKesiapanLintasAwal,
	},
	{
		id: 23,
		name: 'FormKesiapanLintasAwal',
		path: '/app/operational/kesiapanLintas/form',
		page: FormKesiapanLintasAwal,
	},
	{
		id: 23,
		name: 'ViewKesiapanLintasAwal',
		path: '/app/operational/kesiapanLintas/view',
		page: ViewKesiapanLintasAwal,
	},
];

export { dataRouters };
