const URL_API = process.env.REACT_APP_URL_API;
const PING_TARGET = process.env.REACT_APP_URL_API;
const MEDICAL_MICRO_APP = process.env.REACT_APP_MEDICAL_MICRO_APP;
const ADMIN_MICRO_APP = process.env.REACT_APP_WORKORDER_MICRO_APP;
const OPERATIONAL_ASP_MICRO_APP =
  process.env.REACT_APP_OPERATIONAL_ASP_MICRO_APP;
const ASSESSMENT_MICRO_APP = "http://localhost:3003";
const OPERATIONAL_MICRO_APP = "http://localhost:3004";
const REV = "1.0.0";

export default {
  URL_API,
  URL_PHOTO: URL_API + "/uploads",
  PING_TARGET,
  MEDICAL_MICRO_APP,
  ADMIN_MICRO_APP,
  ASSESSMENT_MICRO_APP,
  OPERATIONAL_MICRO_APP,
  OPERATIONAL_ASP_MICRO_APP,
  REV,
};
